#!/usr/bin/env ruby
#encoding: utf-8
# This removes an affiliation paragraph, as LaTeX can generate this from the metadata,
# Word cannot so do not run this for DOCX outputs

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

input = $stdin.read
output = input.gsub(/(^[\*]?Affiliations[^\n]+)/, "\n")

puts output
