#!/usr/bin/env ruby
#encoding: utf-8
# This fixes several problems with LaTeX output

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

input = $stdin.read
# fix some unicode character issues
output = input.gsub(/⬄/, '{\\fixfont⬄}')
output.gsub!(/⇨/, '{\\fixfont⇨}')
output.gsub!(/⇦/, '{\\fixfont⇦}')
output.gsub!(/‐/, '-') # replace hyphen with hyphen-minus
# ensure correct titlecase
output.gsub!(/\bmt\b/i, 'MT')
output.gsub!(/\bteo\b/i, 'TEO')
output.gsub!(/\btrn\b/i, 'TRN')
output.gsub!(/\bmst\b/i, 'MST')
output.gsub!(/\bgaba\b/i, 'GABA')
output.gsub!(/\bgabaergic\b/i, 'GABAergic')
output.gsub!(/\blgn\b/i, 'LGN')
output.gsub!(/\bv1\b/i, 'V1')
output.gsub!(/\bv2\b/i, 'V2')
output.gsub!(/\bv3\b/i, 'V3')
output.gsub!(/\bv4\b/i, 'V4')
# make quotes italicised
output.gsub!(/\\begin\{quote\}/, '\begin{quote}\emph{')
output.gsub!(/\\end\{quote\}/, '}\end{quote}')
# make sure references are small and sans-font
output.gsub!(/\\label{references}/, '\label{references}\setstretch{0.75}\sffamily\small')

puts output
