#!/usr/bin/env ruby
#encoding: utf-8
# This tweaks several parts of the Pandoc LaTeX output

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

output = $stdin.read

# make sure we perform font substitutions for characters that may not have a font entry
# fixfont uses Cambria Math with a huge glyph range
list = %w[⬄ ↔ ⇔ ⇄ ⇨ ⇦ → ← ⇳ Δ ⟳ ⟲ ‐]
list.each do |ch|
  output.gsub!(/#{ch}/, "\{\\fixfont#{ch}\}")
end

# ensure correct titlecase for Neuroscience terms
list = %w[MT MST TEO TRN GABA GABAergic LGN dLGN V1 V2 V3 V4 V5 fMRI EEG MEG]
list.each do |phrase|
  output.gsub!(/\b#{phrase}\b/i, phrase)
end

# make quotes italicised
output.gsub!(/\\begin\{quote\}/, '\begin{quote}\emph{')
output.gsub!(/\\end\{quote\}/, '}\end{quote}')

# make sure references are small and sans-font
output.gsub!(/\\label{references}/, '\label{references}\setstretch{0.75}\sffamily\small')

puts output
