#!/usr/bin/env ruby
# If we have particular metadata, prepend it to a
# paragraph at the start of the document;
# as Word/ODT templates cannot handle this natively

require 'paru/filter'

# here is our list of metadata to convert
prepend_list = {:comments => "Comments", :keywords => "Keywords", :institute => "Affiliations"}

Paru::Filter.run do
  prepend_list.each do |key,val|
    next unless metadata.key?(key.to_s)
    kw = metadata[key]
    text = '**' + val + '**: '
    if kw.is_a?(String)
      text += kw
    elsif kw.is_a?(Array)
      kw.each_index do |i|
        text += kw[i].to_s + ', '
      end
      text = text[0..-3]
    elsif kw[0].is_a?(Hash)
      text = 'HASH TODO'
    end
    p = Paru::PandocFilter::Para.new([])
    p.inner_markdown = text
    document.prepend(p)
  end
  stop!
end